---
title: "Bank-level depositor characteristics and deposit beta"
date: "07/21/2023"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: united
    number_sections: true
    code_folding: hide
---
<style type="text/css">
.main-container {
  max-width: 100%;
  margin-left: auto;
  margin-right: auto;
}

div.main-container {
  max-width: 100%;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```


```{r}
rm(list=ls())
library(data.table)
library(ggplot2)
library(dplyr)
library(stringr)
library(lfe)
library(stargazer)
library(rgdal)
library(rgeos)

data_path = 'C:/Users/dratnadiwakara2/Documents/OneDrive - Louisiana State University/Raw Data/Dewey/'
```

```{r}
appdata <- readRDS("C:/Users/dratnadiwakara2/Documents/OneDrive - Louisiana State University/Raw Data/Dewey/data_ai_data.rds")

names(appdata) <- c('App',	'App_Name',	'App_Icon_Url',	'App_Initial_Release_Date',	'App_Last_Version_Update',	'App_Status',	'Market',	'Market_Name',	'Developer_Account',	'Developer_Account_Name',	'Company',	'Company_Name',	'Company_HQ',	'Company_HQ_Country_Name',	'App_Category',	'App_Category_Name',	'Category',	'Category_Name'
)

appdata <- appdata[Category_Name=="Finance" & Company_HQ_Country_Name=="United States"]

appdata_names <- appdata[,c("Company_Name")]
```


```{r}
sod <- fread("C:/Users/dratnadiwakara2/Documents/OneDrive - Louisiana State University/Raw Data/SOD/data/ALL_2022.csv",select = c("NAMEFULL","NAMEHCR","CERT","RSSDID"))
sod <- sod[!duplicated(sod)]
```

```{r}
library(fuzzyjoin)

result <- stringdist_left_join(appdata_names, sod, by = c("Company_Name" = "NAMEFULL"), method = "jaccard")%>%
  mutate(similarity_score = 1 - stringdist::stringdistmatrix(Company_Name, NAMEFULL, method = "jaccard"))

```

```{r}
result <- appdata_names[, cbind(Company_Name, find_closest_match(Company_Name, sod$NAMEFULL))]
```


```{r}
# Load the required libraries
library(data.table)
library(fuzzyjoin)

# Create sample data.tables
name1 <- data.table(name1 = c("apple", "banana", "orange", "grape"))
name2 <- data.table(name2 = c("apples", "banana", "oranges", "grapes", "kiwi"))

# Perform a fuzzy join and calculate the similarity score
result <- stringdist_left_join(name1, name2, by = c("name1" = "name2"), method = "jaccard")

# Print the result
print(result)


```

